input {
	touchpad{
	   scroll_factor = 0.5
	   natural_scroll = true
	}

}

env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24
# Full screen
bind = , PRINT, exec, hyprshot -m output -o ~/Pictures/Screenshots --clipboard-only=false

# Area selection
bind = SHIFT, PRINT, exec, hyprshot -m region -o ~/Pictures/Screenshots --clipboard-only=false

# Active window (optional)
bind = CTRL, PRINT, exec, hyprshot -m window -o ~/Pictures/Screenshots --clipboard-only=false
